all: mostrarJP crearJP mostrarNJPs

mostrarJP: mostrarJP.c
	gcc -o mostrarJP mostrarJP.c

crearJP: crearJP.c
	gcc -o crearJP crearJP.c

mostrarNJPs: mostrarNJPs.c
	gcc -o mostrarNJPs mostrarNJPs.c

clean:
	rm -f mostrarJP crearJP mostrarNJPs