all: distance Ndistances Mindistance

distance: distance.c
	gcc -o distance distance.c

Ndistances: Ndistances.c
	gcc -o Ndistances Ndistances.c

Mindistance: Mindistance.c
	gcc -o Mindistance Mindistance.c

clean:
	rm distances Ndistances Mindistance